import { TokenData } from "src/market/models";

const tokenData: TokenData[] = [
  {
    name: "Token 1",
    logo: "https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_BTC.svg",
    currencySymbol: "SYM1",
    latestPrice: "100",
    day: "0.01",
    week: "-0.05",
    month: "0.1",
    year: "-0.2",
  },
  {
    name: "Token 2",
    logo: "https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_BTC.svg",
    currencySymbol: "SYM2",
    latestPrice: "200",
    day: "-0.02",
    week: "0.1",
    month: "0.2",
    year: "-0.4",
  },
  {
    name: "Token 3",
    logo: "https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_BTC.svg",
    currencySymbol: "SYM3",
    latestPrice: "300",
    day: "0.03",
    week: "0.15",
    month: "0.3",
    year: "0.6",
  },
  {
    name: "Token 4",
    logo: "https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_BTC.svg",
    currencySymbol: "SYM4",
    latestPrice: "400",
    day: "-0.04",
    week: "0.2",
    month: "-0.4",
    year: "-0.8",
  },
  {
    name: "Token 5",
    logo: "https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_BTC.svg",
    currencySymbol: "SYM5",
    latestPrice: "500",
    day: "0.05",
    week: "0.25",
    month: "0.5",
    year: "1.0",
  },
  {
    name: "Token 6",
    logo: "https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_BTC.svg",
    currencySymbol: "SYM6",
    latestPrice: "600",
    day: "0.06",
    week: "-0.3",
    month: "-0.6",
    year: "1.2",
  },
  {
    name: "Token 7",
    logo: "https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_BTC.svg",
    currencySymbol: "SYM7",
    latestPrice: "700",
    day: "-0.07",
    week: "0.35",
    month: "0.7",
    year: "1.4",
  },
  {
    name: "Token 8",
    logo: "https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_BTC.svg",
    currencySymbol: "SYM8",
    latestPrice: "800",
    day: "0.08",
    week: "0.4",
    month: "0.8",
    year: "1.6",
  },
  {
    name: "Token 9",
    logo: "https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_BTC.svg",
    currencySymbol: "SYM9",
    latestPrice: "900",
    day: "0.09",
    week: "-0.45",
    month: "0.9",
    year: "-1.8",
  },
  {
    name: "Token 10",
    logo: "https://s3-ap-southeast-1.amazonaws.com/static.pintu.co.id/assets/images/logo/circle_BTC.svg",
    currencySymbol: "SYM10",
    latestPrice: "1000",
    day: "0.1",
    week: "-0.5",
    month: "1.0",
    year: "2.0",
  },
];

export { tokenData };
